title: Pathompon(Pam) Moon. 
logo: "/images/picture.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <h3>About Me 3</h3> 
  <p>I am an aspiring data analyst with background in healthcare, specifically in clinical studies. This portfolio contains my projects, demonstrating skills in Excel, R, SQL, and Tableau.<bp>
  <br><br>
  <a href="https://www.linkedin.com/in/pathompon/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
