title: Pathompon Moon. (Pam) # your name (or website title) here
logo: "https://github.com/pammoon14/pammoon14/blob/main/image/20220523_175413_cropped0.png" # your photo (or logo) here
<br><br>
description: > # your text below (remove <br> elements if you don't need line breaks)
 <h2>About Me 2</h2>
  <p>I am an aspiring data analyst with a background in healthcare, specifically in clinical trials and pharmacy.<p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

<p class="view"><a href="https://github.com/chriskhanhtran">View My GitHub Profile</a></p>
<p><small>Hosted on GitHub Pages &mdash; Theme by <a href="https://github.com/orderedlist">orderedlist</a></small></p>
