title: Pathompon Moon. (Pam) # your name (or website title) here
logo: "/image/gitpicture.png?raw=true" # your photo (or logo) here
<br><br>
description: > # your text below (remove <br> elements if you don't need line breaks)
 <h2>About Me 2</h2>
  <p>I am an aspiring data analyst with a background in healthcare, specifically in clinical trials and pharmacy.<p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

